FROM node:20-alpine AS base

WORKDIR /app

COPY package*.json ./
COPY nx.json tsconfig.base.json ./
COPY shared ./shared

RUN npm ci --only=production && npm cache clean --force

FROM base AS build

RUN npm ci

COPY apps/db-client ./apps/db-client

RUN npx nx build db-client --configuration=production

FROM base AS runtime

COPY --from=build /app/dist/apps/db-client ./dist/apps/db-client

WORKDIR /app

EXPOSE 4000

CMD ["node", "dist/apps/db-client/server/server.mjs"]
